from classic.hkdf import hkdf_extract, hkdf_expand

def hybrid_session_key(dh_secret, pq_secret, context=b""):
    """Derive hybrid session key combining classical and post-quantum secrets.
    
    This function:
    1. Concatenates DH and Kyber shared secrets
    2. Applies HKDF-Extract with no salt (defaults to 32 zero bytes)
    3. Applies HKDF-Expand with context-specific info string
    4. Returns 32-byte session key suitable for symmetric encryption/HMAC
    
    Args:
        dh_secret (bytes): 32-byte X25519 shared secret
        pq_secret (bytes): 32-byte ML-KEM-512 shared secret
        context (bytes): Optional context string (e.g., session ID, algorithm negotiation)
                        If provided, appended to info string. Default: empty.
    
    Returns:
        bytes: 32-byte session key combining both secrets
    
    Security Note:
        - If DH is broken (e.g., by quantum computer), Kyber provides security
        - If Kyber is broken, DH provides security  
        - Both must be broken for session key to be compromised (defense-in-depth)
    """
    # Concatenate both secrets
    combined = dh_secret + pq_secret
    
    # HKDF-Extract: derives PRK (pseudo-random key) from combined input
    prk = hkdf_extract(None, combined)
    
    # HKDF-Expand: derives final key material
    # Info string includes context for domain separation (RFC 5869 recommendation)
    info = b"hybrid handshake" + (b"|" + context if context else b"")
    
    return hkdf_expand(prk, info, 32)


# ============================================================================
# NEW CODE: Authenticated Handshake with Digital Signatures
# ============================================================================
# 
# The functions below extend the basic hybrid handshake with server authentication
# using post-quantum digital signatures (Dilithium/ML-DSA).
#
# Authentication Flow:
#   1. Client generates ephemeral DH and Kyber key pairs
#   2. Client sends ephemeral public keys to server
#   3. Server generates ephemeral DH and Kyber key pairs
#   4. Server signs the transcript: client_dh_pub || client_kyber_pub || server_dh_pub || server_kyber_pub
#   5. Server sends ephemeral public keys + signature to client
#   6. Client verifies signature using server's long-term public key
#   7. If verification fails: ABORT handshake (potential MITM attack)
#   8. If verification succeeds: both parties derive shared secrets
#
# After handshake: signatures are no longer used; HMAC protects message integrity
# ============================================================================

from signatures.signatures import sign, verify, build_handshake_transcript


class AuthenticationError(Exception):
    """
    Raised when handshake authentication fails.
    
    Cryptographic Significance:
        This exception indicates that the server's signature over the handshake
        transcript could not be verified. This may indicate:
        - Man-in-the-middle attack (attacker substituted their own keys)
        - Corrupted transmission of signature or public keys
        - Use of wrong server public key for verification
        
    Security Response:
        When this exception is raised, the handshake MUST be aborted.
        No shared secrets should be derived or used.
    """
    pass


def server_sign_handshake(server_signing_private_key, 
                          client_dh_pub, client_kyber_pub,
                          server_dh_pub, server_kyber_pub):
    """
    Server-side: Sign the handshake transcript to authenticate ephemeral keys.
    
    Cryptographic Purpose:
        By signing the transcript of all ephemeral public keys, the server proves:
        1. It possesses the long-term private signing key (authentication)
        2. It endorses these specific ephemeral keys for this session
        3. The keys have not been tampered with since signing
        
        This prevents an attacker from injecting their own ephemeral keys
        into the handshake (man-in-the-middle attack).
    
    Args:
        server_signing_private_key (bytes): Server's long-term Dilithium private key
        client_dh_pub (bytes): Client's ephemeral DH public key (received from client)
        client_kyber_pub (bytes): Client's ephemeral Kyber public key (received from client)
        server_dh_pub (bytes): Server's ephemeral DH public key (generated by server)
        server_kyber_pub (bytes): Server's ephemeral Kyber public key (generated by server)
    
    Returns:
        bytes: Dilithium signature over the handshake transcript
    
    Usage:
        Called by server after generating ephemeral keys, before sending response to client.
    """
    # Build canonical transcript of all ephemeral public keys
    transcript = build_handshake_transcript(
        client_dh_pub, client_kyber_pub,
        server_dh_pub, server_kyber_pub
    )
    
    # Sign transcript with server's long-term identity key
    signature = sign(server_signing_private_key, transcript)
    
    return signature


def client_verify_handshake(server_signing_public_key,
                            client_dh_pub, client_kyber_pub,
                            server_dh_pub, server_kyber_pub,
                            signature):
    """
    Client-side: Verify server's signature before deriving shared secrets.
    
    Cryptographic Purpose:
        Before the client uses the server's ephemeral keys to compute shared
        secrets, it MUST verify that these keys were signed by the legitimate
        server. This is the critical authentication step that prevents MITM attacks.
        
        If verification fails, the handshake must be aborted immediately.
        Proceeding with unverified keys would allow an attacker to:
        - Intercept and decrypt all session traffic
        - Inject malicious messages into the session
    
    Args:
        server_signing_public_key (bytes): Server's long-term Dilithium public key
            (must be obtained through a trusted channel, e.g., certificate)
        client_dh_pub (bytes): Client's ephemeral DH public key (sent by client)
        client_kyber_pub (bytes): Client's ephemeral Kyber public key (sent by client)
        server_dh_pub (bytes): Server's ephemeral DH public key (received from server)
        server_kyber_pub (bytes): Server's ephemeral Kyber public key (received from server)
        signature (bytes): Server's signature over the handshake transcript
    
    Raises:
        AuthenticationError: If signature verification fails
    
    Returns:
        bool: True if verification succeeds (raises exception otherwise)
    
    Usage:
        Called by client after receiving server's response, BEFORE deriving secrets.
    """
    # Reconstruct the same transcript that the server signed
    transcript = build_handshake_transcript(
        client_dh_pub, client_kyber_pub,
        server_dh_pub, server_kyber_pub
    )
    
    # Verify signature using server's long-term public key
    is_valid = verify(server_signing_public_key, transcript, signature)
    
    if not is_valid:
        # CRITICAL: Signature verification failed
        # This may indicate a man-in-the-middle attack
        raise AuthenticationError(
            "Handshake authentication failed: server signature verification failed. "
            "Possible man-in-the-middle attack detected. Handshake aborted."
        )
    
    return True


def authenticated_hybrid_session_key(dh_secret, pq_secret,
                                     server_signing_public_key,
                                     client_dh_pub, client_kyber_pub,
                                     server_dh_pub, server_kyber_pub,
                                     signature):
    """
    Derive hybrid session key only after successful authentication.
    
    Cryptographic Purpose:
        This function combines signature verification with key derivation,
        ensuring that shared secrets are NEVER computed from unverified keys.
        This is a defense-in-depth measure that makes it harder to accidentally
        skip the verification step.
    
    Args:
        dh_secret (bytes): Raw DH shared secret (from X25519 key exchange)
        pq_secret (bytes): Raw Kyber shared secret (from ML-KEM)
        server_signing_public_key (bytes): Server's long-term signing public key
        client_dh_pub (bytes): Client's ephemeral DH public key
        client_kyber_pub (bytes): Client's ephemeral Kyber public key
        server_dh_pub (bytes): Server's ephemeral DH public key
        server_kyber_pub (bytes): Server's ephemeral Kyber public key
        signature (bytes): Server's signature over the handshake transcript
    
    Raises:
        AuthenticationError: If signature verification fails
    
    Returns:
        bytes: 32-byte hybrid session key (only if authentication succeeds)
    
    Security Note:
        After this function returns successfully, the session is authenticated
        and the returned key can be used for symmetric encryption/HMAC.
        The signature is no longer needed; message integrity is now protected by HMAC.
    """
    # STEP 1: Verify server's signature over the handshake transcript
    # This MUST succeed before we derive any session keys
    client_verify_handshake(
        server_signing_public_key,
        client_dh_pub, client_kyber_pub,
        server_dh_pub, server_kyber_pub,
        signature
    )
    
    # STEP 2: Only after successful verification, derive the session key
    # Combines both DH and Kyber secrets for hybrid security
    return hybrid_session_key(dh_secret, pq_secret)
