from primitives.kdf.hkdf import hkdf_extract, hkdf_expand
from primitives import authentication

def hybrid_session_key(dh_secret, pq_secret, context=b""):
    """Derive hybrid session key combining classical and post-quantum secrets.
    
    This function:
    1. Concatenates DH and Kyber shared secrets
    2. Applies HKDF-Extract with no salt (defaults to 32 zero bytes)
    3. Applies HKDF-Expand with context-specific info string
    4. Returns 32-byte session key suitable for symmetric encryption/HMAC
    
    Args:
        dh_secret (bytes): 32-byte X25519 shared secret
        pq_secret (bytes): 32-byte ML-KEM-512 shared secret
        context (bytes): Optional context string (e.g., session ID, algorithm negotiation)
                        If provided, appended to info string. Default: empty.
    
    Returns:
        bytes: 32-byte session key combining both secrets
    
    Security Note:
        - If DH is broken (e.g., by quantum computer), Kyber provides security
        - If Kyber is broken, DH provides security  
        - Both must be broken for session key to be compromised (defense-in-depth)
    """
    # Concatenate both secrets
    combined = dh_secret + pq_secret
    
    # HKDF-Extract: derives PRK (pseudo-random key) from combined input
    prk = hkdf_extract(None, combined)
    
    # HKDF-Expand: derives final key material
    # Info string includes context for domain separation (RFC 5869 recommendation)
    info = b"hybrid handshake" + (b"|" + context if context else b"")
    
    return hkdf_expand(prk, info, 32)


# ============================================================================
# Authenticated Handshake with Dual Signatures (Classical + Post-Quantum)
# ============================================================================
# 
# The functions below implement hybrid handshake authentication
# using DUAL signatures for defense-in-depth security.
#
# Authentication Flow:
#   1. Client generates ephemeral DH and Kyber key pairs
#   2. Client sends ephemeral public keys to server
#   3. Server generates ephemeral DH key and encapsulates to the client's Kyber key
#   4. Server signs the transcript with BOTH ECDSA and Dilithium
#   5. Server sends DH public key + Kyber ciphertext + signatures to client
#   6. Client verifies BOTH signatures using server's long-term keys
#   7. If any signature fails: ABORT handshake (potential MITM attack)
#   8. Client decapsulates; both parties derive shared secrets
#
# After handshake: signatures are no longer used; HMAC protects message integrity
# ============================================================================


class AuthenticationError(Exception):
    """
    Raised when handshake authentication fails.
    
    Cryptographic Significance:
        This exception indicates that either the classical or post-quantum
        (or both) signature over the handshake transcript could not be verified.
        This may indicate:
        - Man-in-the-middle attack (attacker substituted their own keys)
        - Corrupted transmission of signature or public keys
        - Use of wrong server public key for verification
        
    Security Response:
        When this exception is raised, the handshake MUST be aborted.
        No shared secrets should be derived or used.
    """
    pass


def server_sign_handshake(server_signing_private_key_dilithium,
                          server_signing_private_key_ecdsa,
                          client_dh_pub, client_kyber_pub,
                          server_dh_pub, server_kyber_ct):
    """
    Server-side: Sign the handshake transcript with BOTH classical and post-quantum schemes.
    
    Cryptographic Purpose:
        By signing the transcript of all handshake material with both ECDSA and Dilithium,
        the server provides defense-in-depth authentication:
        1. ECDSA signature: Classical authentication (proven, highly studied)
        2. Dilithium signature: Post-quantum authentication (resistant to quantum computers)
        
        Both signatures must verify to authenticate the handshake.
        
        This prevents an attacker from:
        - Injecting their own ephemeral keys (MITM attack)
        - Exploiting weakness in only one signature scheme
    
    Args:
        server_signing_private_key_dilithium (bytes): Server's long-term Dilithium private key
        server_signing_private_key_ecdsa (bytes): Server's long-term ECDSA private key
        client_dh_pub (bytes): Client's ephemeral DH public key (received from client)
        client_kyber_pub (bytes): Client's ephemeral Kyber public key (received from client)
        server_dh_pub (bytes): Server's ephemeral DH public key (generated by server)
        server_kyber_ct (bytes): Server's Kyber ciphertext for the client
    
    Returns:
        tuple: (signature_dilithium: bytes, signature_ecdsa: bytes)
            Two signatures over the same handshake transcript
    
    Usage:
        Called by server after generating ephemeral keys, before sending response to client.
    """
    # Build canonical transcript of all ephemeral public keys
    transcript = authentication.quantum.build_handshake_transcript(
        client_dh_pub, client_kyber_pub,
        server_dh_pub, server_kyber_ct
    )
    
    # Sign transcript with BOTH schemes for defense-in-depth
    signature_dilithium = authentication.quantum.sign(server_signing_private_key_dilithium, transcript)
    signature_ecdsa = authentication.classical.sign(server_signing_private_key_ecdsa, transcript)
    
    return signature_dilithium, signature_ecdsa


def client_verify_handshake(server_signing_public_key_dilithium,
                            server_signing_public_key_ecdsa,
                            client_dh_pub, client_kyber_pub,
                            server_dh_pub, server_kyber_ct,
                            signature_dilithium, signature_ecdsa):
    """
    Client-side: Verify BOTH classical and post-quantum signatures before deriving shared secrets.
    
    Cryptographic Purpose:
        Before the client uses the server's ephemeral keys to compute shared
        secrets, it MUST verify that these keys were signed by BOTH the classical
        (ECDSA) and post-quantum (Dilithium) schemes. This defense-in-depth approach
        ensures that authentication cannot be bypassed by breaking a single algorithm.
        
        The critical authentication step prevents MITM attacks:
        - If ECDSA verifies but Dilithium doesn't: Classical auth works, but PQ is suspect
        - If Dilithium verifies but ECDSA doesn't: PQ auth works, but classical is suspect
        - If both verify: Strongest possible authentication (both classical and PQ are intact)
        
        If verification fails on EITHER scheme, the handshake MUST be aborted immediately.
    
    Args:
        server_signing_public_key_dilithium (bytes): Server's long-term Dilithium public key
        server_signing_public_key_ecdsa (bytes): Server's long-term ECDSA public key
            (both must be obtained through a trusted channel, e.g., certificate)
        client_dh_pub (bytes): Client's ephemeral DH public key (sent by client)
        client_kyber_pub (bytes): Client's ephemeral Kyber public key (sent by client)
        server_dh_pub (bytes): Server's ephemeral DH public key (received from server)
        server_kyber_ct (bytes): Server's Kyber ciphertext (received from server)
        signature_dilithium (bytes): Server's post-quantum signature over handshake transcript
        signature_ecdsa (bytes): Server's classical signature over handshake transcript
    
    Raises:
        AuthenticationError: If either signature verification fails
    
    Returns:
        bool: True if both signatures verify (raises exception otherwise)
    
    Usage:
        Called by client after receiving server's response, BEFORE deriving secrets.
    """
    # Reconstruct the same transcript that the server signed
    transcript = authentication.quantum.build_handshake_transcript(
        client_dh_pub, client_kyber_pub,
        server_dh_pub, server_kyber_ct
    )
    
    # Verify BOTH signatures independently
    is_valid_dilithium = authentication.quantum.verify(server_signing_public_key_dilithium, transcript, signature_dilithium)
    is_valid_ecdsa = authentication.classical.verify(server_signing_public_key_ecdsa, transcript, signature_ecdsa)
    
    # For hybrid authentication to succeed, BOTH must be valid
    if not is_valid_dilithium:
        raise AuthenticationError(
            "Handshake authentication failed: Dilithium (post-quantum) signature verification failed. "
            "Possible post-quantum MITM attack or corrupted PQ signature. Handshake aborted."
        )
    
    if not is_valid_ecdsa:
        raise AuthenticationError(
            "Handshake authentication failed: ECDSA (classical) signature verification failed. "
            "Possible classical MITM attack or corrupted classical signature. Handshake aborted."
        )
    
    return True


def authenticated_hybrid_session_key(dh_secret, pq_secret,
                                     server_signing_public_key_dilithium,
                                     server_signing_public_key_ecdsa,
                                     client_dh_pub, client_kyber_pub,
                                     server_dh_pub, server_kyber_ct,
                                     signature_dilithium, signature_ecdsa):
    """
    Derive hybrid session key only after successful DUAL authentication (classical + PQ).
    
    Cryptographic Purpose:
        This function combines dual hybrid signature verification with key derivation,
        ensuring that shared secrets are NEVER computed from unverified keys.
        This is a defense-in-depth measure that makes it harder to accidentally
        skip the verification step and ensures both authentication schemes succeed.
    
    Args:
        dh_secret (bytes): Raw DH shared secret (from X25519 key exchange)
        pq_secret (bytes): Raw Kyber shared secret (from ML-KEM)
        server_signing_public_key_dilithium (bytes): Server's long-term Dilithium public key
        server_signing_public_key_ecdsa (bytes): Server's long-term ECDSA public key
        client_dh_pub (bytes): Client's ephemeral DH public key
        client_kyber_pub (bytes): Client's ephemeral Kyber public key
        server_dh_pub (bytes): Server's ephemeral DH public key
        server_kyber_ct (bytes): Server's Kyber ciphertext
        signature_dilithium (bytes): Server's post-quantum signature over handshake transcript
        signature_ecdsa (bytes): Server's classical signature over handshake transcript
    
    Raises:
        AuthenticationError: If either signature verification fails
    
    Returns:
        bytes: 32-byte hybrid session key (only if BOTH signatures verify)
    
    Security Note:
        After this function returns successfully, the session is authenticated
        by BOTH classical and post-quantum schemes. The returned key can be used
        for symmetric encryption/HMAC. Signatures are no longer needed.
    """
    # STEP 1: Verify BOTH signatures over the handshake transcript
    # This MUST succeed for both classical and PQ schemes before we derive any session keys
    client_verify_handshake(
        server_signing_public_key_dilithium,
        server_signing_public_key_ecdsa,
        client_dh_pub, client_kyber_pub,
        server_dh_pub, server_kyber_ct,
        signature_dilithium, signature_ecdsa
    )
    
    # STEP 2: Only after successful verification of both schemes, derive the session key
    # Combines both DH and Kyber secrets for hybrid security
    return hybrid_session_key(dh_secret, pq_secret)
